### ISSUE TITLE
DropDown in SideNav not work

### ISSUE THREAD

**Issue by tomsean** [manuel-guilbault/aurelia-materialize#3]
sidenav include dropdown menu,dropdown not work.if you use 'material-dropdown' attr to dropdown element ,and then if you need set closeOnClick=false.but it is not my need .

**Comment by manuel-guilbault** [comment]
@tomsean I think it might be related to [this issue](https://github.com/Dogfalo/materialize/issues/382). I'll check it out.

**Comment by tomsean** [comment]
yes,I have solve this problem by implement collapsible  tool.

**Comment by tomsean** [comment]
can't push to rep

**Comment by manuel-guilbault** [comment]
That's normal, this is how GitHub works. You must send a pull request. If you are not familiar with the subject, I suggest you check the [help page](https://help.github.com/articles/using-pull-requests/).

**Comment by tomsean** [comment]
yes,I other rep can ,but this rep work error,repsone with 403 error.and then I search info about 403 error,all the mothed not work for me.
![Uploading 20150617093753.png…]()
