### ISSUE TITLE
Upgrade to Materialize 0.97

### ISSUE THREAD

**Issue by tlvenn** [manuel-guilbault/aurelia-materialize#5]
Materialize has been updated and then it's time to upgrade on dep. I weird thing, right now I cant seem to pull the 0.97 version at all with jspm. The cli does not seem to be able to parse the package.json anymore...

**Comment by flieks** [comment]
this was a bug but is fixed now
see [issue](https://github.com/Dogfalo/materialize/issues/1637)
i tested it

**Comment by tlvenn** [comment]
Yes it is indeed fixed now.
