### ISSUE TITLE
Please update link in README

### ISSUE THREAD

**Issue by Thanood** [manuel-guilbault/aurelia-materialize#9]
Hello Manuel,

your README states that "The official repository has been moved" - now that repository has been moved, too. :smile: 

Could you change the link to the following repo?
https://github.com/aurelia-ui-toolkits/aurelia-materialize-bridge

That would be great, thanks. :smile: 

Of course, you're also invited to contribute there if you like.

**Comment by manuel-guilbault** [comment]
@Thanood done!

**Comment by Thanood** [comment]
Great, thanks.
